#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Feb 20, 2026 02:35:46 PM GMT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import unknown

_debug = True # False to eliminate debug printing from callback functions.

def operate(n1,op,n2):
    return eval(f'{n1}{op}{n2}')

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = unknown.Toplevel1(_top1)
    assign_commands()

    root.mainloop()

def assign_commands():
    global field
    field = 1
    for x in range(10):
        i = 9-x
        btn = getattr(_w1, f"Button{x+1}")
        btn.config(command=lambda d=str(i): press_number(d), text=str(i))

    _w1.plusBtn.config(command=lambda: press_operator("+"))
    _w1.minusBtn.config(command=lambda: press_operator("-"))
    _w1.mulBtn.config(command=lambda: press_operator("*"))
    _w1.divBtn.config(command=lambda: press_operator("/"))
def press_number(digit):
    if field == 1:
        _w1.Entry1.config(text=str(_w1.Entry1.cget('text'))+digit)
    else:
        _w1.Entry3.config(text=str(_w1.Entry3.cget('text'))+digit)
def press_operator(op):
    _w1.Entry2.config(text=str(op))
    global field
    field = 2
def calc():
    ans = operate(_w1.Entry1.cget('text'),_w1.Entry2.cget('text'),_w1.Entry3.cget('text'))
    _w1.Entry1.config(text='')
    _w1.Entry2.config(text='')
    _w1.Entry3.config(text='')
    _w1.Label4.config(text=ans)
    global field
    field = 1
def num1():
    global field
    field = 1
def num2():
    global field
    field = 2
if __name__ == '__main__':
    unknown.start_up()




