#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Feb 20, 2026 08:36:43 AM GMT  platform: Linux
#    Feb 20, 2026 08:40:31 AM GMT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import unknown

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = unknown.Toplevel1(_top1)
    root.mainloop()

def login_btn_command(*args):
    username = w.username_entry.get()
    password = w.password_entry.get()
    if username == 'scooterking38' and password == 'hello':
        w.result_label.config(text='yes')
    else:
        w.result_label.config(config='no')

if __name__ == '__main__':
    unknown.start_up()





