#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Feb 20, 2026 05:19:29 PM GMT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import unknown_support

_bgcolor = 'skyblue1'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
     def __init__(self, top=None):
          '''This class configures and populates the toplevel window.
             top is the toplevel containing window.'''

          top.geometry("968x429+952+101")
          top.minsize(1, 1)
          top.maxsize(3825, 1050)
          top.resizable(1,  1)
          top.title("Toplevel 0")
          top.configure(background="skyblue1")
          top.configure(highlightbackground="skyblue1")
          top.configure(highlightcolor="black")

          self.top = top

          self.Button2 = tk.Button(self.top)
          self.Button2.place(relx=0.316, rely=0.152, height=33, width=71)
          self.Button2.configure(activebackground="#d9d9d9")
          self.Button2.configure(background="skyblue1")
          self.Button2.configure(compound='left')
          self.Button2.configure(disabledforeground="#659bbf")
          self.Button2.configure(highlightbackground="skyblue1")
          self.Button2.configure(text='''Button''')

          self.Button5 = tk.Button(self.top)
          self.Button5.place(relx=0.316, rely=0.228, height=33, width=71)
          self.Button5.configure(activebackground="#d9d9d9")
          self.Button5.configure(background="skyblue1")
          self.Button5.configure(compound='left')
          self.Button5.configure(disabledforeground="#659bbf")
          self.Button5.configure(highlightbackground="skyblue1")
          self.Button5.configure(text='''Button''')

          self.Button8 = tk.Button(self.top)
          self.Button8.place(relx=0.316, rely=0.303, height=33, width=71)
          self.Button8.configure(activebackground="#d9d9d9")
          self.Button8.configure(background="skyblue1")
          self.Button8.configure(compound='left')
          self.Button8.configure(disabledforeground="#659bbf")
          self.Button8.configure(highlightbackground="skyblue1")
          self.Button8.configure(text='''Button''')

          self.plusBtn = tk.Button(self.top)
          self.plusBtn.place(relx=0.47, rely=0.152, height=33, width=71)
          self.plusBtn.configure(activebackground="#d9d9d9")
          self.plusBtn.configure(background="skyblue1")
          self.plusBtn.configure(compound='left')
          self.plusBtn.configure(disabledforeground="#659bbf")
          self.plusBtn.configure(highlightbackground="skyblue1")
          self.plusBtn.configure(text='''+''')

          self.minusBtn = tk.Button(self.top)
          self.minusBtn.place(relx=0.47, rely=0.228, height=33, width=71)
          self.minusBtn.configure(activebackground="#d9d9d9")
          self.minusBtn.configure(background="skyblue1")
          self.minusBtn.configure(compound='left')
          self.minusBtn.configure(disabledforeground="#659bbf")
          self.minusBtn.configure(highlightbackground="skyblue1")
          self.minusBtn.configure(text='''-''')

          self.mulBtn = tk.Button(self.top)
          self.mulBtn.place(relx=0.47, rely=0.303, height=33, width=71)
          self.mulBtn.configure(activebackground="#d9d9d9")
          self.mulBtn.configure(background="skyblue1")
          self.mulBtn.configure(compound='left')
          self.mulBtn.configure(disabledforeground="#659bbf")
          self.mulBtn.configure(highlightbackground="skyblue1")
          self.mulBtn.configure(text='''*''')

          self.divBtn = tk.Button(self.top)
          self.divBtn.place(relx=0.47, rely=0.38, height=33, width=71)
          self.divBtn.configure(activebackground="#d9d9d9")
          self.divBtn.configure(background="skyblue1")
          self.divBtn.configure(compound='left')
          self.divBtn.configure(disabledforeground="#659bbf")
          self.divBtn.configure(highlightbackground="skyblue1")
          self.divBtn.configure(text='''/''')

          self.Button10 = tk.Button(self.top)
          self.Button10.place(relx=0.393, rely=0.38, height=33, width=71)
          self.Button10.configure(activebackground="#d9d9d9")
          self.Button10.configure(background="skyblue1")
          self.Button10.configure(compound='left')
          self.Button10.configure(disabledforeground="#659bbf")
          self.Button10.configure(highlightbackground="skyblue1")
          self.Button10.configure(text='''Button''')

          self.Button1 = tk.Button(self.top)
          self.Button1.place(relx=0.393, rely=0.152, height=33, width=71)
          self.Button1.configure(activebackground="#d9d9d9")
          self.Button1.configure(background="skyblue1")
          self.Button1.configure(compound='left')
          self.Button1.configure(disabledforeground="#659bbf")
          self.Button1.configure(highlightbackground="skyblue1")
          self.Button1.configure(text='''Button''')

          self.Button3 = tk.Button(self.top)
          self.Button3.place(relx=0.24, rely=0.152, height=33, width=71)
          self.Button3.configure(activebackground="#d9d9d9")
          self.Button3.configure(background="skyblue1")
          self.Button3.configure(compound='left')
          self.Button3.configure(disabledforeground="#659bbf")
          self.Button3.configure(highlightbackground="skyblue1")
          self.Button3.configure(text='''Button''')

          self.Button4 = tk.Button(self.top)
          self.Button4.place(relx=0.393, rely=0.228, height=33, width=71)
          self.Button4.configure(activebackground="#d9d9d9")
          self.Button4.configure(background="skyblue1")
          self.Button4.configure(compound='left')
          self.Button4.configure(disabledforeground="#659bbf")
          self.Button4.configure(highlightbackground="skyblue1")
          self.Button4.configure(text='''Button''')

          self.Button6 = tk.Button(self.top)
          self.Button6.place(relx=0.24, rely=0.228, height=33, width=71)
          self.Button6.configure(activebackground="#d9d9d9")
          self.Button6.configure(background="skyblue1")
          self.Button6.configure(compound='left')
          self.Button6.configure(disabledforeground="#659bbf")
          self.Button6.configure(highlightbackground="skyblue1")
          self.Button6.configure(text='''Button''')

          self.Button7 = tk.Button(self.top)
          self.Button7.place(relx=0.393, rely=0.303, height=33, width=71)
          self.Button7.configure(activebackground="#d9d9d9")
          self.Button7.configure(background="skyblue1")
          self.Button7.configure(compound='left')
          self.Button7.configure(disabledforeground="#659bbf")
          self.Button7.configure(highlightbackground="skyblue1")
          self.Button7.configure(text='''Button''')

          self.Button9 = tk.Button(self.top)
          self.Button9.place(relx=0.24, rely=0.303, height=33, width=71)
          self.Button9.configure(activebackground="#d9d9d9")
          self.Button9.configure(background="skyblue1")
          self.Button9.configure(compound='left')
          self.Button9.configure(disabledforeground="#659bbf")
          self.Button9.configure(highlightbackground="skyblue1")
          self.Button9.configure(text='''Button''')

          self.num2 = tk.Button(self.top)
          self.num2.place(relx=0.316, rely=0.38, height=33, width=71)
          self.num2.configure(activebackground="#d9d9d9")
          self.num2.configure(background="skyblue1")
          self.num2.configure(command=unknown_support.num2)
          self.num2.configure(compound='left')
          self.num2.configure(disabledforeground="#659bbf")
          self.num2.configure(highlightbackground="skyblue1")
          self.num2.configure(text='''num2''')

          self.Label2 = tk.Label(self.top)
          self.Label2.place(relx=0.316, rely=0.019, height=22, width=78)
          self.Label2.configure(activebackground="#d9d9d9")
          self.Label2.configure(anchor='w')
          self.Label2.configure(background="#ff0000")
          self.Label2.configure(compound='left')
          self.Label2.configure(disabledforeground="#659bbf")
          self.Label2.configure(highlightbackground="skyblue1")
          self.Label2.configure(text='''operator''')

          self.Label3 = tk.Label(self.top)
          self.Label3.place(relx=0.393, rely=0.019, height=22, width=65)
          self.Label3.configure(activebackground="#d9d9d9")
          self.Label3.configure(anchor='w')
          self.Label3.configure(background="#ff0000")
          self.Label3.configure(compound='left')
          self.Label3.configure(disabledforeground="#659bbf")
          self.Label3.configure(highlightbackground="skyblue1")
          self.Label3.configure(text='''num2''')

          self.Label1 = tk.Label(self.top)
          self.Label1.place(relx=0.24, rely=0.019, height=22, width=76)
          self.Label1.configure(activebackground="#d9d9d9")
          self.Label1.configure(anchor='w')
          self.Label1.configure(background="#ff0000")
          self.Label1.configure(compound='left')
          self.Label1.configure(disabledforeground="#659bbf")
          self.Label1.configure(highlightbackground="skyblue1")
          self.Label1.configure(text='''num1''')

          self.Entry1 = tk.Label(self.top)
          self.Entry1.place(relx=0.24, rely=0.084, height=23, width=62)
          self.Entry1.configure(activebackground="#d9d9d9")
          self.Entry1.configure(anchor='w')
          self.Entry1.configure(background="#ffffff")
          self.Entry1.configure(compound='left')
          self.Entry1.configure(disabledforeground="#659bbf")
          self.Entry1.configure(highlightbackground="skyblue1")

          self.Entry3 = tk.Label(self.top)
          self.Entry3.place(relx=0.393, rely=0.084, height=23, width=62)
          self.Entry3.configure(activebackground="#d9d9d9")
          self.Entry3.configure(anchor='w')
          self.Entry3.configure(background="#ffffff")
          self.Entry3.configure(compound='left')
          self.Entry3.configure(disabledforeground="#659bbf")
          self.Entry3.configure(highlightbackground="skyblue1")

          self.Entry2 = tk.Label(self.top)
          self.Entry2.place(relx=0.316, rely=0.084, height=23, width=66)
          self.Entry2.configure(activebackground="#d9d9d9")
          self.Entry2.configure(anchor='w')
          self.Entry2.configure(background="#ffffff")
          self.Entry2.configure(compound='left')
          self.Entry2.configure(disabledforeground="#659bbf")
          self.Entry2.configure(highlightbackground="skyblue1")

          self.num1 = tk.Button(self.top)
          self.num1.place(relx=0.24, rely=0.38, height=33, width=71)
          self.num1.configure(activebackground="#d9d9d9")
          self.num1.configure(background="skyblue1")
          self.num1.configure(command=unknown_support.num1)
          self.num1.configure(compound='left')
          self.num1.configure(disabledforeground="#659bbf")
          self.num1.configure(highlightbackground="skyblue1")
          self.num1.configure(text='''num1''')

          self.Label4 = tk.Label(self.top)
          self.Label4.place(relx=0.24, rely=0.455, height=34, width=210)
          self.Label4.configure(activebackground="#d9d9d9")
          self.Label4.configure(anchor='w')
          self.Label4.configure(background="#ffffff")
          self.Label4.configure(borderwidth="10")
          self.Label4.configure(compound='left')
          self.Label4.configure(disabledforeground="#659bbf")
          self.Label4.configure(highlightbackground="skyblue1")

          self.calc = tk.Button(self.top)
          self.calc.place(relx=0.47, rely=0.455, height=43, width=71)
          self.calc.configure(activebackground="#d9d9d9")
          self.calc.configure(background="#a6ffe7")
          self.calc.configure(command=unknown_support.calc)
          self.calc.configure(compound='left')
          self.calc.configure(disabledforeground="#659bbf")
          self.calc.configure(highlightbackground="skyblue1")
          self.calc.configure(text='''calculate''')

def start_up():
     unknown_support.main()

if __name__ == '__main__':
     unknown_support.main()




