#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Feb 20, 2026 08:40:40 AM GMT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import unknown_support

_bgcolor = '#d9d9d9'
_fgcolor = '#000000'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x399+2087+1080")
        top.minsize(1, 1)
        top.maxsize(3825, 1050)
        top.resizable(1,  1)
        top.title("Toplevel 0")

        self.top = top

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=0.15, rely=0.1, height=23, width=79)
        self.Label1.configure(activebackground="#d9d9d9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(compound='left')
        self.Label1.configure(text='''Username:''')

        self.Label2 = tk.Label(self.top)
        self.Label2.place(relx=0.15, rely=0.226, height=23, width=79)
        self.Label2.configure(activebackground="#d9d9d9")
        self.Label2.configure(anchor='w')
        self.Label2.configure(compound='left')
        self.Label2.configure(text='''Password:''')

        self.result_label = tk.Label(self.top)
        self.result_label.place(relx=0.267, rely=0.576, height=23, width=39)
        self.result_label.configure(activebackground="#d9d9d9")
        self.result_label.configure(anchor='w')
        self.result_label.configure(compound='left')
        self.result_label.configure(text='''result''')

        self.username_entry = tk.Entry(self.top)
        self.username_entry.place(relx=0.3, rely=0.1, height=25, relwidth=0.143)
        self.username_entry.configure(background="#d9d9d9")
        self.username_entry.configure(exportselection="0")
        self.username_entry.configure(font="TkFixedFont")
        self.username_entry.configure(selectbackground="#d9d9d9")

        self.password_entry = tk.Entry(self.top)
        self.password_entry.place(relx=0.3, rely=0.226, height=25
                , relwidth=0.143)
        self.password_entry.configure(background="#d9d9d9")
        self.password_entry.configure(exportselection="0")
        self.password_entry.configure(font="TkFixedFont")
        self.password_entry.configure(selectbackground="#d9d9d9")
        self.password_entry.configure(show="*")

        self.login_btn = tk.Button(self.top)
        self.login_btn.place(relx=0.25, rely=0.376, height=33, width=71)
        self.login_btn.configure(activebackground="#d9d9d9")
        self.login_btn.configure(command=unknown_support.login_btn_command)
        self.login_btn.configure(compound='left')
        self.login_btn.configure(text='''Login''')

def start_up():
    unknown_support.main()

if __name__ == '__main__':
    unknown_support.main()




